// Tone styles — recalibrated for dark graphite surfaces.
// Background opacities are higher than on white because dark bg absorbs light.
export const TONE_STYLES = {
 critical: {
  text: 'text-danger',
  bg: 'bg-danger/[0.14]',
  bgSubtle: 'bg-danger/[0.08]',
  border: 'border-danger/40',
  borderSoft: 'border-danger/25',
  borderStrong: 'border-danger',
  borderLeft: 'border-l-danger',
  borderBottom: 'border-b-danger',
  dot: 'bg-danger',
  pill: 'text-danger bg-danger/[0.14]',
 },
 danger: {
  text: 'text-danger',
  bg: 'bg-danger/[0.14]',
  bgSubtle: 'bg-danger/[0.08]',
  border: 'border-danger/40',
  borderSoft: 'border-danger/25',
  borderStrong: 'border-danger',
  borderLeft: 'border-l-danger',
  borderBottom: 'border-b-danger',
  dot: 'bg-danger',
  pill: 'text-danger bg-danger/[0.14]',
 },
 warn: {
  text: 'text-warn',
  bg: 'bg-warn/[0.18]',
  bgSubtle: 'bg-warn/[0.08]',
  border: 'border-warn/40',
  borderSoft: 'border-warn/25',
  borderStrong: 'border-warn',
  borderLeft: 'border-l-warn',
  borderBottom: 'border-b-warn',
  dot: 'bg-warn',
  pill: 'text-warn bg-warn/[0.18]',
 },
 ok: {
  text: 'text-ok',
  bg: 'bg-ok/[0.18]',
  bgSubtle: 'bg-ok/[0.08]',
  border: 'border-ok/40',
  borderSoft: 'border-ok/25',
  borderStrong: 'border-ok',
  borderLeft: 'border-l-ok',
  borderBottom: 'border-b-ok',
  dot: 'bg-ok',
  pill: 'text-ok bg-ok/[0.18]',
 },
 info: {
  text: 'text-muted',
  bg: 'bg-stone3',
  bgSubtle: 'bg-stone2',
  border: 'border-rule',
  borderSoft: 'border-rule2',
  borderStrong: 'border-rule',
  borderLeft: 'border-l-rule',
  borderBottom: 'border-b-rule',
  dot: 'bg-muted',
  pill: 'text-muted bg-stone3',
 },
 muted: {
  text: 'text-muted',
  bg: 'bg-stone3',
  bgSubtle: 'bg-stone2',
  border: 'border-rule',
  borderSoft: 'border-rule2',
  borderStrong: 'border-rule',
  borderLeft: 'border-l-rule',
  borderBottom: 'border-b-rule',
  dot: 'bg-muted',
  pill: 'text-muted bg-stone3',
 },
 int: {
  text: 'text-ochre',
  bg: 'bg-ochre/[0.14]',
  bgSubtle: 'bg-ochre/[0.07]',
  border: 'border-ochre/40',
  borderSoft: 'border-ochre/25',
  borderStrong: 'border-ochre',
  borderLeft: 'border-l-ochre',
  borderBottom: 'border-b-ochre',
  dot: 'bg-ochre',
  pill: 'text-ochre bg-ochre/[0.14]',
 },
 alert: {
  text: 'text-ink',
  bg: 'bg-danger',
  bgSubtle: 'bg-danger',
  border: 'border-danger',
  borderSoft: 'border-danger',
  borderStrong: 'border-danger',
  borderLeft: 'border-l-danger',
  borderBottom: 'border-b-danger',
  dot: 'bg-ink',
  pill: 'text-ink bg-danger',
 },
}

export function toneStyle(tone = 'muted', part = 'pill') {
 return TONE_STYLES[tone]?.[part] || TONE_STYLES.muted[part]
}
