export const TONE_STYLES = {
 critical: {
  text: 'text-danger',
  bg: 'bg-danger/[0.04]',
  bgSubtle: 'bg-danger/[0.03]',
  border: 'border-danger/30',
  borderSoft: 'border-danger/20',
  borderStrong: 'border-danger',
  borderLeft: 'border-l-danger',
  borderBottom: 'border-b-danger',
  dot: 'bg-danger',
  pill: 'text-danger bg-danger/[0.04]',
 },
 danger: {
  text: 'text-danger',
  bg: 'bg-danger/[0.04]',
  bgSubtle: 'bg-danger/[0.03]',
  border: 'border-danger/30',
  borderSoft: 'border-danger/20',
  borderStrong: 'border-danger',
  borderLeft: 'border-l-danger',
  borderBottom: 'border-b-danger',
  dot: 'bg-danger',
  pill: 'text-danger bg-danger/[0.04]',
 },
 warn: {
  text: 'text-warn',
  bg: 'bg-warn/10',
  bgSubtle: 'bg-warn/[0.03]',
  border: 'border-warn/30',
  borderSoft: 'border-warn/20',
  borderStrong: 'border-warn',
  borderLeft: 'border-l-warn',
  borderBottom: 'border-b-warn',
  dot: 'bg-warn',
  pill: 'text-warn bg-warn/10',
 },
 ok: {
  text: 'text-ok',
  bg: 'bg-ok/10',
  bgSubtle: 'bg-ok/[0.03]',
  border: 'border-ok/30',
  borderSoft: 'border-ok/20',
  borderStrong: 'border-ok',
  borderLeft: 'border-l-ok',
  borderBottom: 'border-b-ok',
  dot: 'bg-ok',
  pill: 'text-ok bg-ok/10',
 },
 info: {
  text: 'text-muted',
  bg: 'bg-stone3',
  bgSubtle: 'bg-stone2',
  border: 'border-rule2',
  borderSoft: 'border-rule2',
  borderStrong: 'border-rule',
  borderLeft: 'border-l-rule2',
  borderBottom: 'border-b-rule2',
  dot: 'bg-muted',
  pill: 'text-muted bg-stone3',
 },
 muted: {
  text: 'text-muted',
  bg: 'bg-stone3',
  bgSubtle: 'bg-stone2',
  border: 'border-rule2',
  borderSoft: 'border-rule2',
  borderStrong: 'border-rule',
  borderLeft: 'border-l-rule2',
  borderBottom: 'border-b-rule2',
  dot: 'bg-muted',
  pill: 'text-muted bg-stone3',
 },
 int: {
  text: 'text-ochre',
  bg: 'bg-ochre/10',
  bgSubtle: 'bg-ochre/[0.03]',
  border: 'border-ochre/30',
  borderSoft: 'border-ochre/20',
  borderStrong: 'border-ochre',
  borderLeft: 'border-l-ochre',
  borderBottom: 'border-b-ochre',
  dot: 'bg-ochre',
  pill: 'text-ochre bg-ochre/10',
 },
 alert: {
  text: 'text-white',
  bg: 'bg-danger',
  bgSubtle: 'bg-danger',
  border: 'border-danger',
  borderSoft: 'border-danger',
  borderStrong: 'border-danger',
  borderLeft: 'border-l-danger',
  borderBottom: 'border-b-danger',
  dot: 'bg-white',
  pill: 'text-white bg-danger',
 },
}

export function toneStyle(tone = 'muted', part = 'pill') {
 return TONE_STYLES[tone]?.[part] || TONE_STYLES.muted[part]
}
